# Generated by Django 4.2.1 on 2023-05-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otp',
            table='otp',
        ),
    ]
