# Generated by Django 4.2.1 on 2023-05-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_city_country_countrylanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
