# Generated by Django 4.2.1 on 2023-05-20 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_otp_doc_alter_otp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='doc',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 22, 13, 37, 243576, tzinfo=datetime.timezone.utc)),
        ),
    ]
