# Generated by Django 4.2.1 on 2023-05-20 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_otp_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='doc',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 22, 49, 12, 65257, tzinfo=datetime.timezone.utc)),
        ),
    ]
