# Generated by Django 4.2.1 on 2023-05-20 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_otp_doc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='otp',
            name='doc',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 22, 51, 36, 913053, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
