# Generated by Django 4.2.1 on 2023-05-21 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_customuser_options_alter_otp_doc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='otp',
            name='doc',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 15, 12, 18, 864600, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='user',
        ),
    ]
